import type {
  Lead,
  LeadStage,
  LeadTimelineEvent,
} from "./types";

/**
 * Seed leads for the Sales workspace. Hand-crafted so the timelines tell a
 * coherent story (stages move forward over time) and the stage distribution
 * mirrors what a real pipeline looks like — most in early stages, a couple
 * closed, one or two hot.
 */

function ts(daysAgo: number, hour = 10, minute = 0): string {
  const d = new Date("2026-05-05T00:00:00.000Z");
  d.setUTCDate(d.getUTCDate() - daysAgo);
  d.setUTCHours(hour, minute, 0, 0);
  return d.toISOString();
}

function buildTimeline(
  leadId: string,
  ownerId: string,
  rows: Array<Partial<LeadTimelineEvent> & { type: LeadTimelineEvent["type"] }>,
): LeadTimelineEvent[] {
  return rows.map((r, i) => ({
    id: `${leadId}_t${i + 1}`,
    actorId: ownerId,
    timestamp: r.timestamp ?? ts(7 - i),
    ...r,
  }));
}

export const leads: Lead[] = [
  {
    id: "lead_001",
    clinicName: "32 Pearly White Dental Clinic",
    doctorName: "Dr. Anika Rao",
    specialization: "Dentistry",
    phone: "9240214452",
    city: "Hyderabad",
    area: "Gachibowli",
    address: "Garg's Vivanta, Plot No.4, Telecom Nagar, 500032",
    stage: "subscription-closed",
    source: "referral",
    value: 12_000,
    monthlyAppointments: 220,
    branches: 1,
    notes:
      "Strong referral from Dr. Sharma. Wants the full patient-comms suite from day one.",
    ownerId: "u_arjun",
    lastActivityAt: ts(0, 9, 14),
    nextAction: "Send onboarding kit and schedule kickoff.",
    timeline: buildTimeline("lead_001", "u_arjun", [
      { type: "stage-change", fromStage: "cold-lead", toStage: "first-contact", timestamp: ts(11, 11) },
      { type: "call", durationSec: 312, content: "Intro call — interested, asked for case studies.", timestamp: ts(10, 14) },
      { type: "stage-change", fromStage: "first-contact", toStage: "doctor-meeting", timestamp: ts(8, 10) },
      { type: "meeting", content: "Met Dr. Rao at her clinic. Showed product demo.", timestamp: ts(7, 16) },
      { type: "stage-change", fromStage: "doctor-meeting", toStage: "pitch-delivered", timestamp: ts(6, 12) },
      { type: "note", content: "Sent commercial proposal. Awaiting partner approval.", timestamp: ts(4, 17) },
      { type: "stage-change", fromStage: "pitch-delivered", toStage: "hot-lead", timestamp: ts(2, 9) },
      { type: "stage-change", fromStage: "hot-lead", toStage: "subscription-closed", timestamp: ts(0, 9, 14) },
    ]),
  },
  {
    id: "lead_002",
    clinicName: "Arcus Clinic",
    doctorName: "Dr. Vivek Reddy",
    specialization: "General Physician",
    phone: "8795462310",
    city: "Vijayawada",
    area: "Kukatpally",
    address: "1st floor, LIG 61/8, KPHB Phase 4, 500072",
    stage: "pitch-delivered",
    source: "cold",
    value: 2_490,
    monthlyAppointments: 90,
    branches: 1,
    notes: "Receptionist is the gatekeeper — schedule directly with her.",
    ownerId: "u_kavya",
    lastActivityAt: ts(0, 5, 30),
    nextAction: null,
    timeline: buildTimeline("lead_002", "u_kavya", [
      { type: "stage-change", fromStage: "cold-lead", toStage: "first-contact", timestamp: ts(6, 11) },
      { type: "call", durationSec: 187, content: "Cold call. Receptionist scheduled doctor callback.", timestamp: ts(6, 11, 5) },
      { type: "stage-change", fromStage: "first-contact", toStage: "doctor-meeting", timestamp: ts(5, 14) },
      { type: "meeting", content: "Doctor available 12 mins, walked through key features.", timestamp: ts(4, 16) },
      { type: "stage-change", fromStage: "doctor-meeting", toStage: "first-contact", timestamp: ts(3, 9) },
      { type: "stage-change", fromStage: "first-contact", toStage: "pitch-delivered", timestamp: ts(0, 5, 30) },
    ]),
  },
  {
    id: "lead_003",
    clinicName: "Apollo Family Medical Center",
    doctorName: "Dr. Srinivas Kumar",
    specialization: "Family Medicine",
    phone: "9240219102",
    city: "Hyderabad",
    area: "Banjara Hills",
    address: "Plot 23, Road No. 12, Banjara Hills, 500034",
    stage: "hot-lead",
    source: "inbound",
    value: 38_500,
    monthlyAppointments: 480,
    branches: 3,
    notes:
      "Three-branch chain. Decision needs both Dr. Kumar and his ops manager.",
    ownerId: "u_arjun",
    lastActivityAt: ts(1, 11, 20),
    nextAction: "Negotiate multi-branch discount.",
    timeline: buildTimeline("lead_003", "u_arjun", [
      { type: "stage-change", fromStage: "cold-lead", toStage: "first-contact", timestamp: ts(14, 10) },
      { type: "note", content: "Inbound from website — looking for tools to onboard 3 new branches.", timestamp: ts(14, 10, 5) },
      { type: "call", durationSec: 624, content: "Discovery call with Dr. Kumar and his admin.", timestamp: ts(12, 14) },
      { type: "stage-change", fromStage: "first-contact", toStage: "doctor-meeting", timestamp: ts(10, 11) },
      { type: "meeting", content: "Onsite demo at Banjara Hills office.", timestamp: ts(8, 15) },
      { type: "stage-change", fromStage: "doctor-meeting", toStage: "pitch-delivered", timestamp: ts(6, 17) },
      { type: "stage-change", fromStage: "pitch-delivered", toStage: "hot-lead", timestamp: ts(1, 11, 20) },
    ]),
  },
  {
    id: "lead_004",
    clinicName: "Sai Krishna Dental",
    doctorName: "Dr. Lakshmi Devi",
    specialization: "Dentistry",
    phone: "9240221344",
    city: "Hyderabad",
    area: "Khairatabad",
    address: "5-9-22, Secretariat Rd, Saifabad, 500004",
    stage: "doctor-meeting",
    source: "referral",
    value: 6_800,
    monthlyAppointments: 150,
    branches: 2,
    notes: "Concerned about patient-flow tracking — emphasise dashboards.",
    ownerId: "u_sanjay",
    lastActivityAt: ts(2, 16, 5),
    nextAction: "Follow up on patient-flow concerns by Wed.",
    timeline: buildTimeline("lead_004", "u_sanjay", [
      { type: "stage-change", fromStage: "cold-lead", toStage: "first-contact", timestamp: ts(9, 12) },
      { type: "call", durationSec: 240, content: "Referred by Dr. Anika — happy to chat next week.", timestamp: ts(9, 12, 4) },
      { type: "stage-change", fromStage: "first-contact", toStage: "doctor-meeting", timestamp: ts(2, 16, 5) },
    ]),
  },
  {
    id: "lead_005",
    clinicName: "Yashoda Multispecialty",
    doctorName: "Dr. Manish Kapoor",
    specialization: "Multispecialty",
    phone: "9824012783",
    city: "Bengaluru",
    area: "Indiranagar",
    address: "Indiranagar 2nd Stage, HAL 2nd Stage, 560038",
    stage: "first-contact",
    source: "event",
    value: 0,
    monthlyAppointments: 700,
    branches: 4,
    notes: "Met at Healthcare India Expo. Send pre-meeting brief.",
    ownerId: "u_kavya",
    lastActivityAt: ts(3, 14, 30),
    nextAction: "Email pre-meeting brief by Mon.",
    timeline: buildTimeline("lead_005", "u_kavya", [
      { type: "stage-change", fromStage: "cold-lead", toStage: "first-contact", timestamp: ts(3, 14, 30) },
      { type: "note", content: "Met at Healthcare India Expo. Card on file.", timestamp: ts(3, 14, 32) },
    ]),
  },
  {
    id: "lead_006",
    clinicName: "Sunshine Children's Clinic",
    doctorName: "Dr. Ramya Iyer",
    specialization: "Pediatrics",
    phone: "9824018990",
    city: "Bengaluru",
    area: "Jayanagar",
    address: "742, 11th Main Rd, 4th Block, Jayanagar, 560011",
    stage: "cold-lead",
    source: "cold",
    value: 0,
    monthlyAppointments: 0,
    branches: 1,
    notes: "Phone went to voicemail. Try email next.",
    ownerId: "u_arjun",
    lastActivityAt: ts(5, 10, 0),
    nextAction: "Try email — phone went to voicemail.",
    timeline: buildTimeline("lead_006", "u_arjun", [
      { type: "call", durationSec: 22, content: "No answer. Left voicemail.", timestamp: ts(5, 10, 0) },
    ]),
  },
  {
    id: "lead_007",
    clinicName: "Lotus Ayurveda",
    doctorName: "Dr. Pankaj Joshi",
    specialization: "Ayurveda",
    phone: "9819220067",
    city: "Pune",
    area: "Baner",
    address: "Survey No. 14, Baner Rd, near Chandani Chowk, 411045",
    stage: "pitch-delivered",
    source: "inbound",
    value: 14_200,
    monthlyAppointments: 260,
    branches: 2,
    notes: "Liked the patient app. Pricing comparison vs. competitor pending.",
    ownerId: "u_sanjay",
    lastActivityAt: ts(1, 18, 10),
    nextAction: null,
    timeline: buildTimeline("lead_007", "u_sanjay", [
      { type: "stage-change", fromStage: "cold-lead", toStage: "first-contact", timestamp: ts(8, 11) },
      { type: "stage-change", fromStage: "first-contact", toStage: "doctor-meeting", timestamp: ts(5, 14) },
      { type: "meeting", content: "Demo via Google Meet. Doctor liked the patient-app.", timestamp: ts(5, 14, 30) },
      { type: "stage-change", fromStage: "doctor-meeting", toStage: "pitch-delivered", timestamp: ts(1, 18, 10) },
    ]),
  },
  {
    id: "lead_008",
    clinicName: "Vasant ENT Care",
    doctorName: "Dr. Suresh Vasant",
    specialization: "ENT",
    phone: "9819228812",
    city: "Mumbai",
    area: "Andheri West",
    address: "Shop 4, Manish Nagar, J.P. Road, Andheri (West), 400053",
    stage: "subscription-closed",
    source: "referral",
    value: 9_400,
    monthlyAppointments: 175,
    branches: 1,
    notes: "Closed via co-founder intro. Onboarding next week.",
    ownerId: "u_arjun",
    lastActivityAt: ts(2, 11, 45),
    nextAction: "Onboarding handover scheduled for tomorrow.",
    timeline: buildTimeline("lead_008", "u_arjun", [
      { type: "stage-change", fromStage: "cold-lead", toStage: "first-contact", timestamp: ts(20, 10) },
      { type: "stage-change", fromStage: "first-contact", toStage: "doctor-meeting", timestamp: ts(15, 12) },
      { type: "stage-change", fromStage: "doctor-meeting", toStage: "pitch-delivered", timestamp: ts(10, 16) },
      { type: "stage-change", fromStage: "pitch-delivered", toStage: "hot-lead", timestamp: ts(5, 14) },
      { type: "stage-change", fromStage: "hot-lead", toStage: "subscription-closed", timestamp: ts(2, 11, 45) },
    ]),
  },
  {
    id: "lead_009",
    clinicName: "Rainbow Pediatrics",
    doctorName: "Dr. Latha Subramaniam",
    specialization: "Pediatrics",
    phone: "9787019456",
    city: "Chennai",
    area: "Nungambakkam",
    address: "31 Cathedral Rd, Sterling Rd, Nungambakkam, 600086",
    stage: "first-contact",
    source: "website",
    value: 0,
    monthlyAppointments: 0,
    branches: 2,
    notes: "Web form: 'interested in patient management for pediatric clinic'.",
    ownerId: "u_kavya",
    lastActivityAt: ts(4, 9, 50),
    nextAction: "Send case study deck.",
    timeline: buildTimeline("lead_009", "u_kavya", [
      { type: "note", content: "Web form: 'interested in patient management for pediatric clinic'.", timestamp: ts(4, 9, 30) },
      { type: "stage-change", fromStage: "cold-lead", toStage: "first-contact", timestamp: ts(4, 9, 50) },
    ]),
  },
  {
    id: "lead_010",
    clinicName: "Be Skin Hair Clinic",
    doctorName: "Dr. Prudhvi Raj",
    specialization: "Dermatology",
    phone: "9240218861",
    city: "Hyderabad",
    area: "Hitech City",
    address: "S8, 2nd floor, Bizness Square, Hitech City Main Rd, 500081",
    stage: "doctor-meeting",
    source: "referral",
    value: 4_200,
    monthlyAppointments: 95,
    branches: 1,
    notes: "Co-founder is the budget owner. Loop her in for next meeting.",
    ownerId: "u_sanjay",
    lastActivityAt: ts(1, 13, 15),
    nextAction: "Confirm meeting with co-founder next Tue.",
    timeline: buildTimeline("lead_010", "u_sanjay", [
      { type: "stage-change", fromStage: "cold-lead", toStage: "first-contact", timestamp: ts(7, 12) },
      { type: "call", durationSec: 405, content: "Walked through main features.", timestamp: ts(7, 12, 7) },
      { type: "stage-change", fromStage: "first-contact", toStage: "doctor-meeting", timestamp: ts(1, 13, 15) },
    ]),
  },
  {
    id: "lead_011",
    clinicName: "Surya Eye Care",
    doctorName: "Dr. Rohan Surya",
    specialization: "Ophthalmology",
    phone: "8765432109",
    city: "Coimbatore",
    area: "RS Puram",
    address: "112 Race Course Rd, RS Puram, Coimbatore, 641002",
    stage: "hot-lead",
    source: "inbound",
    value: 17_000,
    monthlyAppointments: 320,
    branches: 2,
    notes: "Doctor's spouse runs ops — needs sign-off too.",
    ownerId: "u_arjun",
    lastActivityAt: ts(0, 8, 5),
    nextAction: "Final pricing call — Dr. agreed in principle.",
    timeline: buildTimeline("lead_011", "u_arjun", [
      { type: "stage-change", fromStage: "cold-lead", toStage: "first-contact", timestamp: ts(13, 11) },
      { type: "stage-change", fromStage: "first-contact", toStage: "doctor-meeting", timestamp: ts(9, 14) },
      { type: "stage-change", fromStage: "doctor-meeting", toStage: "pitch-delivered", timestamp: ts(4, 16) },
      { type: "note", content: "Doctor's spouse runs ops — needs sign-off too.", timestamp: ts(3, 11) },
      { type: "stage-change", fromStage: "pitch-delivered", toStage: "hot-lead", timestamp: ts(0, 8, 5) },
    ]),
  },
  {
    id: "lead_012",
    clinicName: "Mangala Maternity Home",
    doctorName: "Dr. Mangala Bhat",
    specialization: "Obstetrics & Gynecology",
    phone: "9999881122",
    city: "Pune",
    area: "Kothrud",
    address: "Plot 47, Karve Road, Kothrud, Pune, 411038",
    stage: "cold-lead",
    source: "cold",
    value: 0,
    monthlyAppointments: 0,
    branches: 1,
    notes: "Cold-call gatekept. Try LinkedIn intro before next call.",
    ownerId: "u_kavya",
    lastActivityAt: ts(8, 15, 0),
    nextAction: "Try LinkedIn intro before next call.",
    timeline: buildTimeline("lead_012", "u_kavya", [
      { type: "call", durationSec: 38, content: "Receptionist asked us to call back next week.", timestamp: ts(8, 15, 0) },
    ]),
  },
];

export function getLead(id: string): Lead | undefined {
  return leads.find((l) => l.id === id);
}

// Render-friendly metadata for stages — kept beside the data so the UI can
// stay generic.

export const LEAD_STAGE_LABEL: Record<LeadStage, string> = {
  "cold-lead": "Cold lead",
  "first-contact": "First contact",
  "doctor-meeting": "Doctor meeting",
  "pitch-delivered": "Pitch delivered",
  "hot-lead": "Hot lead",
  "sprint-started": "Sprint started",
  "sprint-review": "Sprint review",
  "subscription-closed": "Subscription closed",
  lost: "Lost",
};

/** Stages in workflow order — used by the stage-change Select. */
export const LEAD_STAGE_ORDER: LeadStage[] = [
  "cold-lead",
  "first-contact",
  "doctor-meeting",
  "pitch-delivered",
  "hot-lead",
  "sprint-started",
  "sprint-review",
  "subscription-closed",
  "lost",
];

export const LEAD_SOURCE_LABEL: Record<Lead["source"], string> = {
  cold: "Cold",
  referral: "Referral",
  inbound: "Inbound",
  event: "Event",
  website: "Website",
};
